import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// The guide itself: one Markdown file per section, ordered by `order`.
const sections = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/sections' }),
  schema: z.object({
    title: z.string(),
    kicker: z.string(),
    order: z.number(),
    summary: z.string(),
  }),
});

// Neighborhood entries. The same shape will feed the v2 swipe deck, so the
// fields are deliberately structured rather than free prose.
const neighborhoods = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/neighborhoods' }),
  schema: z.object({
    name: z.string(),
    vibe: z.array(z.string()),
    oneLine: z.string(),
    transit: z.string(),
  }),
});

// Saved Google Maps lists, generated by `npm run import:lists` from a Takeout
// export. The schema is the contract between that importer and the pages: if a
// place comes back without coordinates the build fails here rather than
// shipping a map with a hole in it.
const place = z.object({
  name: z.string(),
  note: z.string().optional(),
  url: z.string().url().optional(),
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  address: z.string().optional(),
  source: z.enum(['url', 'nominatim']).optional(),
  blurb: z.string().optional(),
  cover: z.string().optional(),
  tags: z.array(z.string()).optional(),
  kinds: z.array(z.string()).optional(),
});

const lists = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/data/lists' }),
  schema: z.object({
    name: z.string(),
    slug: z.string(),
    emoji: z.string().optional(),
    blurb: z.string().optional(),
    cover: z.string().optional(),
    order: z.number().default(99),
    hidden: z.boolean().default(false),
    curated: z.boolean().default(false),
    updated: z.string().optional(),
    places: z.array(place),
  }),
});

export const collections = { sections, neighborhoods, lists };
